In [ ]:
#Converting a list to n-dimensional NumPy array
import numpy as np
mylist = [12,'orange', 1234567,'36578562']
print(mylist)
numpy_arr = np.array(mylist)
print(numpy_arr)

[12, 'orange', 1234567, '36578562']
['12' 'orange' '1234567' '36578562']


In [ ]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
print(arr1[2])
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr2[1:3])

3
[[6 7 8 9 0]]


In [ ]:
arr= np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
print(arr[2,1,1])
print(arr[1:])
print(arr[::2])
print(arr.shape)


23
[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
(3, 3, 3)


In [ ]:
print(arr[1:])


[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
(3, 3, 3)


In [ ]:
print(arr[::2])
print(arr.shape)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
(3, 3, 3)


In [ ]:
import numpy as np
m = int(input("Enter m:"))
n = int(input("enter n:"))
p = int(input("enter p:"))
arr1 = []
for i in range(m):
  for j in range(p):
    arr1.append(int(input("enter a value of matrix:")))
arr1 = np.array(arr1)
ar1 = arr1.reshape(m,p)
print(ar1)
arr2 = []
for i in range(n):
  for j in range(p):
    arr2.append(int(input("Enter value of 2nd matrix:")))
arr2 = np.array(arr2)
ar2 = arr2.reshape(n,p)
print(ar2)
arr3 = np.concatenate((ar1, ar2), axis = 0)
print("Final ans:")
print(arr3)

Enter m:3
enter n:2
enter p:4
enter a value of matrix:1
enter a value of matrix:2
enter a value of matrix:3
enter a value of matrix:4
enter a value of matrix:5
enter a value of matrix:6
enter a value of matrix:7
enter a value of matrix:8
enter a value of matrix:9
enter a value of matrix:10
enter a value of matrix:11
enter a value of matrix:12
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Enter value of 2nd matrix:13
Enter value of 2nd matrix:14
Enter value of 2nd matrix:15
Enter value of 2nd matrix:16
Enter value of 2nd matrix:17
Enter value of 2nd matrix:18
Enter value of 2nd matrix:19
Enter value of 2nd matrix:20
[[13 14 15 16]
 [17 18 19 20]]
Final ans:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [ ]:
test_str = "aaabbbcccd"
all_freq = {}
  
for i in test_str:
    if i in all_freq:
        all_freq[i] += 1
    else:
        all_freq[i] = 1
print(all_freq)

{'a': 3, 'b': 3, 'c': 3, 'd': 1}
